<?php

use Illuminate\Database\Seeder;
use App\Municipio;

class MunicipioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['state_id' => 1, 'name' => 'Ahuachapan', 'city_code' => '01'],
            ['state_id' => 1, 'name' => 'Apaneca', 'city_code' => '02'],
            ['state_id' => 1, 'name' => 'Atiquizaya', 'city_code' => '03'],
            ['state_id' => 1, 'name' => 'Concepcion de Ataco', 'city_code' => '04'],
            ['state_id' => 1, 'name' => 'El Refugio', 'city_code' => '05'],
            ['state_id' => 1, 'name' => 'Guaymango', 'city_code' => '06'],
            ['state_id' => 1, 'name' => 'Jujutla', 'city_code' => '07'],
            ['state_id' => 1, 'name' => 'San Lorenzo', 'city_code' => '08'],
            ['state_id' => 1, 'name' => 'San Francisco Menendez', 'city_code' => '09'],
            ['state_id' => 1, 'name' => 'San Pedro Puxtla', 'city_code' => '10'],
            ['state_id' => 1, 'name' => 'Tacuba', 'city_code' => '11'],
            ['state_id' => 1, 'name' => 'Turin', 'city_code' => '12'],
            ['state_id' => 2, 'name' => 'Santa Ana', 'city_code' => '01'],
            ['state_id' => 2, 'name' => 'Candelaria de la Frontera', 'city_code' => '02'],
            ['state_id' => 2, 'name' => 'Chalchuapa', 'city_code' => '03'],
            ['state_id' => 2, 'name' => 'Coatepeque', 'city_code' => '04'],
            ['state_id' => 2, 'name' => 'El Congo', 'city_code' => '05'],
            ['state_id' => 2, 'name' => 'El Porvenir', 'city_code' => '06'],
            ['state_id' => 2, 'name' => 'Masahuat', 'city_code' => '07'],
            ['state_id' => 2, 'name' => 'Metapan', 'city_code' => '08'],
            ['state_id' => 2, 'name' => 'San Antonio Pajonal', 'city_code' => '09'],
            ['state_id' => 2, 'name' => 'San Sebastian Salitrillo', 'city_code' => '10'],
            ['state_id' => 2, 'name' => 'Santa Rosa Guachipilin', 'city_code' => '11'],
            ['state_id' => 2, 'name' => 'Santiago de la Frontera', 'city_code' => '12'],
            ['state_id' => 2, 'name' => 'Texistepeque', 'city_code' => '13'],
            ['state_id' => 3, 'name' => 'Sonsonate', 'city_code' => '01'],
            ['state_id' => 3, 'name' => 'Acajutla', 'city_code' => '02'],
            ['state_id' => 3, 'name' => 'Armenia', 'city_code' => '03'],
            ['state_id' => 3, 'name' => 'Caluco', 'city_code' => '04'],
            ['state_id' => 3, 'name' => 'Cuisnahuat', 'city_code' => '05'],
            ['state_id' => 3, 'name' => 'Izalco', 'city_code' => '06'],
            ['state_id' => 3, 'name' => 'Juayua', 'city_code' => '07'],
            ['state_id' => 3, 'name' => 'Nahuizalco', 'city_code' => '08'],
            ['state_id' => 3, 'name' => 'Nahulingo', 'city_code' => '09'],
            ['state_id' => 3, 'name' => 'Salcoatitan', 'city_code' => '10'],
            ['state_id' => 3, 'name' => 'San Antonio del Monte', 'city_code' => '11'],
            ['state_id' => 3, 'name' => 'San Julian', 'city_code' => '12'],
            ['state_id' => 3, 'name' => 'Santa Catarina Masahuat', 'city_code' => '13'],
            ['state_id' => 3, 'name' => 'Santa Isabel Ishuatan', 'city_code' => '14'],
            ['state_id' => 3, 'name' => 'Santo Domingo de Guzman', 'city_code' => '15'],
            ['state_id' => 3, 'name' => 'Sonzacate', 'city_code' => '16'],
            ['state_id' => 4, 'name' => 'Santa Tecla', 'city_code' => '01'],
            ['state_id' => 4, 'name' => 'Antiguo Cuscatlan', 'city_code' => '02'],
            ['state_id' => 4, 'name' => 'Chiltiupan', 'city_code' => '03'],
            ['state_id' => 4, 'name' => 'Ciudad Arce', 'city_code' => '04'],
            ['state_id' => 4, 'name' => 'Colon', 'city_code' => '05'],
            ['state_id' => 4, 'name' => 'Comasagua', 'city_code' => '06'],
            ['state_id' => 4, 'name' => 'Huizucar', 'city_code' => '07'],
            ['state_id' => 4, 'name' => 'Jayaque', 'city_code' => '08'],
            ['state_id' => 4, 'name' => 'Jicalapa', 'city_code' => '09'],
            ['state_id' => 4, 'name' => 'La Libertad', 'city_code' => '10'],
            ['state_id' => 4, 'name' => 'Nuevo Cuscatlan', 'city_code' => '11'],
            ['state_id' => 4, 'name' => 'Quezaltepeque', 'city_code' => '12'],
            ['state_id' => 4, 'name' => 'San Juan Opico', 'city_code' => '13'],
            ['state_id' => 4, 'name' => 'Sacacoyo', 'city_code' => '14'],
            ['state_id' => 4, 'name' => 'San Jose Villanueva', 'city_code' => '15'],
            ['state_id' => 4, 'name' => 'San Matias', 'city_code' => '16'],
            ['state_id' => 4, 'name' => 'San Pablo Tacachico', 'city_code' => '17'],
            ['state_id' => 4, 'name' => 'Talnique', 'city_code' => '18'],
            ['state_id' => 4, 'name' => 'Tamanique', 'city_code' => '19'],
            ['state_id' => 4, 'name' => 'Teotepeque', 'city_code' => '20'],
            ['state_id' => 4, 'name' => 'Tepecoyo', 'city_code' => '21'],
            ['state_id' => 4, 'name' => 'Zaragoza', 'city_code' => '22'],
            ['state_id' => 5, 'name' => 'San Salvador', 'city_code' => '01'],
            ['state_id' => 5, 'name' => 'Aguilares', 'city_code' => '02'],
            ['state_id' => 5, 'name' => 'Apopa', 'city_code' => '03'],
            ['state_id' => 5, 'name' => 'Ayutuxtepeque', 'city_code' => '04'],
            ['state_id' => 5, 'name' => 'Cuscatancingo', 'city_code' => '05'],
            ['state_id' => 5, 'name' => 'Ciudad Delgado', 'city_code' => '06'],
            ['state_id' => 5, 'name' => 'El Paisnal', 'city_code' => '07'],
            ['state_id' => 5, 'name' => 'Guazapa', 'city_code' => '08'],
            ['state_id' => 5, 'name' => 'Ilopango', 'city_code' => '09'],
            ['state_id' => 5, 'name' => 'Mejicanos', 'city_code' => '10'],
            ['state_id' => 5, 'name' => 'Nejapa', 'city_code' => '11'],
            ['state_id' => 5, 'name' => 'Panchimalco', 'city_code' => '12'],
            ['state_id' => 5, 'name' => 'Rosario de Mora', 'city_code' => '13'],
            ['state_id' => 5, 'name' => 'San Marcos', 'city_code' => '14'],
            ['state_id' => 5, 'name' => 'San Martin', 'city_code' => '15'],
            ['state_id' => 5, 'name' => 'Santiago Texacuangos', 'city_code' => '16'],
            ['state_id' => 5, 'name' => 'Santo Tomas', 'city_code' => '17'],
            ['state_id' => 5, 'name' => 'Soyapango', 'city_code' => '18'],
            ['state_id' => 5, 'name' => 'Tonacatepeque', 'city_code' => '19'],
            ['state_id' => 6, 'name' => 'Chalatenango', 'city_code' => '01'],
            ['state_id' => 6, 'name' => 'Agua Caliente', 'city_code' => '02'],
            ['state_id' => 6, 'name' => 'Arcatao', 'city_code' => '03'],
            ['state_id' => 6, 'name' => 'Azacualpa', 'city_code' => '04'],
            ['state_id' => 6, 'name' => 'Cancasque', 'city_code' => '05'],
            ['state_id' => 6, 'name' => 'Citala', 'city_code' => '06'],
            ['state_id' => 6, 'name' => 'Comalapa', 'city_code' => '07'],
            ['state_id' => 6, 'name' => 'Concepcion Quezaltepeque', 'city_code' => '08'],
            ['state_id' => 6, 'name' => 'Dulce Nombre de Maria', 'city_code' => '09'],
            ['state_id' => 6, 'name' => 'El Carrizal', 'city_code' => '10'],
            ['state_id' => 6, 'name' => 'El Paraiso', 'city_code' => '11'],
            ['state_id' => 6, 'name' => 'La Laguna', 'city_code' => '12'],
            ['state_id' => 6, 'name' => 'La Palma', 'city_code' => '13'],
            ['state_id' => 6, 'name' => 'La Reina', 'city_code' => '14'],
            ['state_id' => 6, 'name' => 'San Jose de Las Flores', 'city_code' => '15'],
            ['state_id' => 6, 'name' => 'Las Vueltas', 'city_code' => '16'],
            ['state_id' => 6, 'name' => 'Nombre de Jesus', 'city_code' => '17'],
            ['state_id' => 6, 'name' => 'Nueva Concepcion', 'city_code' => '18'],
            ['state_id' => 6, 'name' => 'Nueva Trinidad', 'city_code' => '19'],
            ['state_id' => 6, 'name' => 'Ojos de Agua', 'city_code' => '20'],
            ['state_id' => 6, 'name' => 'Potonico', 'city_code' => '21'],
            ['state_id' => 6, 'name' => 'San Antonio de la Cruz', 'city_code' => '22'],
            ['state_id' => 6, 'name' => 'San Antonio Los Ranchos', 'city_code' => '23'],
            ['state_id' => 6, 'name' => 'San Fernando', 'city_code' => '24'],
            ['state_id' => 6, 'name' => 'San Francisco Lempa', 'city_code' => '25'],
            ['state_id' => 6, 'name' => 'San Francisco Morazan', 'city_code' => '26'],
            ['state_id' => 6, 'name' => 'San Ignacio', 'city_code' => '27'],
            ['state_id' => 6, 'name' => 'San Isidro Labrador', 'city_code' => '28'],
            ['state_id' => 6, 'name' => 'San Luis del Carmen', 'city_code' => '29'],
            ['state_id' => 6, 'name' => 'San Miguel de Mercedes', 'city_code' => '30'],
            ['state_id' => 6, 'name' => 'San Rafael', 'city_code' => '31'],
            ['state_id' => 6, 'name' => 'Santa Rita', 'city_code' => '32'],
            ['state_id' => 6, 'name' => 'Tejutla', 'city_code' => '33'],
            ['state_id' => 7, 'name' => 'Cojutepeque', 'city_code' => '01'],
            ['state_id' => 7, 'name' => 'Candelaria', 'city_code' => '02'],
            ['state_id' => 7, 'name' => 'El Carmen', 'city_code' => '03'],
            ['state_id' => 7, 'name' => 'El Rosario', 'city_code' => '04'],
            ['state_id' => 7, 'name' => 'Monte San Juan', 'city_code' => '05'],
            ['state_id' => 7, 'name' => 'Oratorio de Concepcion', 'city_code' => '06'],
            ['state_id' => 7, 'name' => 'San Bartolome Perulapia', 'city_code' => '07'],
            ['state_id' => 7, 'name' => 'San Cristobal', 'city_code' => '08'],
            ['state_id' => 7, 'name' => 'San Jose Guayabal', 'city_code' => '09'],
            ['state_id' => 7, 'name' => 'San Pedro Perulapan', 'city_code' => '10'],
            ['state_id' => 7, 'name' => 'San Rafael Cedros', 'city_code' => '11'],
            ['state_id' => 7, 'name' => 'San Ramon', 'city_code' => '12'],
            ['state_id' => 7, 'name' => 'Santa Cruz Analquito', 'city_code' => '13'],
            ['state_id' => 7, 'name' => 'Santa Cruz Michapa', 'city_code' => '14'],
            ['state_id' => 7, 'name' => 'Suchitoto', 'city_code' => '15'],
            ['state_id' => 7, 'name' => 'Tenancingo', 'city_code' => '16'],
            ['state_id' => 8, 'name' => 'Zacatecoluca', 'city_code' => '01'],
            ['state_id' => 8, 'name' => 'Cuyultitan', 'city_code' => '02'],
            ['state_id' => 8, 'name' => 'El Rosario', 'city_code' => '03'],
            ['state_id' => 8, 'name' => 'Jerusalen', 'city_code' => '04'],
            ['state_id' => 8, 'name' => 'Mercedes La Ceiba', 'city_code' => '05'],
            ['state_id' => 8, 'name' => 'Olocuilta', 'city_code' => '06'],
            ['state_id' => 8, 'name' => 'Paraiso de Osorio', 'city_code' => '07'],
            ['state_id' => 8, 'name' => 'San Antonio Masahuat', 'city_code' => '08'],
            ['state_id' => 8, 'name' => 'San Emigdio', 'city_code' => '09'],
            ['state_id' => 8, 'name' => 'San Francisco Chinameca', 'city_code' => '10'],
            ['state_id' => 8, 'name' => 'San Pedro Masahuat', 'city_code' => '11'],
            ['state_id' => 8, 'name' => 'San Juan Nonualco', 'city_code' => '12'],
            ['state_id' => 8, 'name' => 'San Juan Talpa', 'city_code' => '13'],
            ['state_id' => 8, 'name' => 'San Juan Tepezontes', 'city_code' => '14'],
            ['state_id' => 8, 'name' => 'San Luis La Herradura', 'city_code' => '15'],
            ['state_id' => 8, 'name' => 'San Luis Talpa', 'city_code' => '16'],
            ['state_id' => 8, 'name' => 'San Miguel Tepezontes', 'city_code' => '17'],
            ['state_id' => 8, 'name' => 'San Pedro Nonualco', 'city_code' => '18'],
            ['state_id' => 8, 'name' => 'San Rafael Obrajuelo', 'city_code' => '19'],
            ['state_id' => 8, 'name' => 'Santa Maria Ostuma', 'city_code' => '20'],
            ['state_id' => 8, 'name' => 'Santiago Nonualco', 'city_code' => '21'],
            ['state_id' => 8, 'name' => 'Tapalhuaca', 'city_code' => '22'],
            ['state_id' => 9, 'name' => 'Sensuntepeque', 'city_code' => '01'],
            ['state_id' => 9, 'name' => 'Cinquera', 'city_code' => '02'],
            ['state_id' => 9, 'name' => 'Dolores', 'city_code' => '03'],
            ['state_id' => 9, 'name' => 'Guacotecti', 'city_code' => '04'],
            ['state_id' => 9, 'name' => 'Ilobasco', 'city_code' => '05'],
            ['state_id' => 9, 'name' => 'Jutiapa', 'city_code' => '06'],
            ['state_id' => 9, 'name' => 'San Isidro', 'city_code' => '07'],
            ['state_id' => 9, 'name' => 'Tejutepeque', 'city_code' => '08'],
            ['state_id' => 9, 'name' => 'Victoria', 'city_code' => '09'],
            ['state_id' => 10, 'name' => 'San Vicente', 'city_code' => '01'],
            ['state_id' => 10, 'name' => 'Apastepeque', 'city_code' => '02'],
            ['state_id' => 10, 'name' => 'Guadalupe', 'city_code' => '03'],
            ['state_id' => 10, 'name' => 'San Cayetano Istepeque', 'city_code' => '04'],
            ['state_id' => 10, 'name' => 'San Esteban Catarina', 'city_code' => '05'],
            ['state_id' => 10, 'name' => 'San Ildefonso', 'city_code' => '06'],
            ['state_id' => 10, 'name' => 'San Lorenzo', 'city_code' => '07'],
            ['state_id' => 10, 'name' => 'San Sebastian', 'city_code' => '08'],
            ['state_id' => 10, 'name' => 'Santa Clara', 'city_code' => '09'],
            ['state_id' => 10, 'name' => 'Santo Domingo', 'city_code' => '10'],
            ['state_id' => 10, 'name' => 'Tecoluca', 'city_code' => '11'],
            ['state_id' => 10, 'name' => 'Tepetitan', 'city_code' => '12'],
            ['state_id' => 10, 'name' => 'Verapaz', 'city_code' => '13'],
            ['state_id' => 11, 'name' => 'Usulutan', 'city_code' => '01'],
            ['state_id' => 11, 'name' => 'Alegria', 'city_code' => '02'],
            ['state_id' => 11, 'name' => 'Berlin', 'city_code' => '03'],
            ['state_id' => 11, 'name' => 'California', 'city_code' => '04'],
            ['state_id' => 11, 'name' => 'Concepcion Batres', 'city_code' => '05'],
            ['state_id' => 11, 'name' => 'El Triunfo', 'city_code' => '06'],
            ['state_id' => 11, 'name' => 'Ereguayquin', 'city_code' => '07'],
            ['state_id' => 11, 'name' => 'Estanzuelas', 'city_code' => '08'],
            ['state_id' => 11, 'name' => 'Jiquilisco', 'city_code' => '09'],
            ['state_id' => 11, 'name' => 'Jucuapa', 'city_code' => '10'],
            ['state_id' => 11, 'name' => 'Jucuaran', 'city_code' => '11'],
            ['state_id' => 11, 'name' => 'Mercedes Umaña', 'city_code' => '12'],
            ['state_id' => 11, 'name' => 'Nueva Granada', 'city_code' => '13'],
            ['state_id' => 11, 'name' => 'Ozatlan', 'city_code' => '14'],
            ['state_id' => 11, 'name' => 'Puerto El Triunfo', 'city_code' => '15'],
            ['state_id' => 11, 'name' => 'San Agustin', 'city_code' => '16'],
            ['state_id' => 11, 'name' => 'San Buenaventura', 'city_code' => '17'],
            ['state_id' => 11, 'name' => 'San Dionisio', 'city_code' => '18'],
            ['state_id' => 11, 'name' => 'San Francisco Javier', 'city_code' => '19'],
            ['state_id' => 11, 'name' => 'Santa Elena', 'city_code' => '20'],
            ['state_id' => 11, 'name' => 'Santa Maria', 'city_code' => '21'],
            ['state_id' => 11, 'name' => 'Santiago de Maria', 'city_code' => '22'],
            ['state_id' => 11, 'name' => 'Tecapan', 'city_code' => '23'],
            ['state_id' => 12, 'name' => 'San Miguel', 'city_code' => '01'],
            ['state_id' => 12, 'name' => 'Carolina', 'city_code' => '02'],
            ['state_id' => 12, 'name' => 'Chapeltique', 'city_code' => '03'],
            ['state_id' => 12, 'name' => 'Chinameca', 'city_code' => '04'],
            ['state_id' => 12, 'name' => 'Chirilagua', 'city_code' => '05'],
            ['state_id' => 12, 'name' => 'Ciudad Barrios', 'city_code' => '06'],
            ['state_id' => 12, 'name' => 'Comacaran', 'city_code' => '07'],
            ['state_id' => 12, 'name' => 'El Transito', 'city_code' => '08'],
            ['state_id' => 12, 'name' => 'Lolotique', 'city_code' => '09'],
            ['state_id' => 12, 'name' => 'Moncagua', 'city_code' => '10'],
            ['state_id' => 12, 'name' => 'Nueva Guadalupe', 'city_code' => '11'],
            ['state_id' => 12, 'name' => 'Nuevo Eden de San Juan', 'city_code' => '12'],
            ['state_id' => 12, 'name' => 'Quelepa', 'city_code' => '13'],
            ['state_id' => 12, 'name' => 'San Antonio del Mosco', 'city_code' => '14'],
            ['state_id' => 12, 'name' => 'San Gerardo', 'city_code' => '15'],
            ['state_id' => 12, 'name' => 'San Jorge', 'city_code' => '16'],
            ['state_id' => 12, 'name' => 'San Luis de la Reina', 'city_code' => '17'],
            ['state_id' => 12, 'name' => 'San Rafael Oriente', 'city_code' => '18'],
            ['state_id' => 12, 'name' => 'Sesori', 'city_code' => '19'],
            ['state_id' => 12, 'name' => 'Uluazapa', 'city_code' => '20'],
            ['state_id' => 13, 'name' => 'San Francisco Gotera', 'city_code' => '01'],
            ['state_id' => 13, 'name' => 'Arambala', 'city_code' => '02'],
            ['state_id' => 13, 'name' => 'Cacaopera', 'city_code' => '03'],
            ['state_id' => 13, 'name' => 'Chilanga', 'city_code' => '04'],
            ['state_id' => 13, 'name' => 'Corinto', 'city_code' => '05'],
            ['state_id' => 13, 'name' => 'Delicias de Concepcion', 'city_code' => '06'],
            ['state_id' => 13, 'name' => 'El Divisadero', 'city_code' => '07'],
            ['state_id' => 13, 'name' => 'El Rosario', 'city_code' => '08'],
            ['state_id' => 13, 'name' => 'Gualococti', 'city_code' => '09'],
            ['state_id' => 13, 'name' => 'Guatajiagua', 'city_code' => '10'],
            ['state_id' => 13, 'name' => 'Joateca', 'city_code' => '11'],
            ['state_id' => 13, 'name' => 'Jocoaitique', 'city_code' => '12'],
            ['state_id' => 13, 'name' => 'Jocoro', 'city_code' => '13'],
            ['state_id' => 13, 'name' => 'Lolotiquillo', 'city_code' => '14'],
            ['state_id' => 13, 'name' => 'Meanguera', 'city_code' => '15'],
            ['state_id' => 13, 'name' => 'Osicala', 'city_code' => '16'],
            ['state_id' => 13, 'name' => 'Perquin', 'city_code' => '17'],
            ['state_id' => 13, 'name' => 'San Carlos', 'city_code' => '18'],
            ['state_id' => 13, 'name' => 'San Fernando', 'city_code' => '19'],
            ['state_id' => 13, 'name' => 'San Isidro', 'city_code' => '20'],
            ['state_id' => 13, 'name' => 'San Simon', 'city_code' => '21'],
            ['state_id' => 13, 'name' => 'Sensembra', 'city_code' => '22'],
            ['state_id' => 13, 'name' => 'Sociedad', 'city_code' => '23'],
            ['state_id' => 13, 'name' => 'Torola', 'city_code' => '24'],
            ['state_id' => 13, 'name' => 'Yamabal', 'city_code' => '25'],
            ['state_id' => 13, 'name' => 'Yoloaiquin', 'city_code' => '26'],
            ['state_id' => 14, 'name' => 'La Union', 'city_code' => '01'],
            ['state_id' => 14, 'name' => 'Anamoros', 'city_code' => '02'],
            ['state_id' => 14, 'name' => 'Bolivar', 'city_code' => '03'],
            ['state_id' => 14, 'name' => 'Concepcion de Oriente', 'city_code' => '04'],
            ['state_id' => 14, 'name' => 'Conchagua', 'city_code' => '05'],
            ['state_id' => 14, 'name' => 'El Carmen', 'city_code' => '06'],
            ['state_id' => 14, 'name' => 'El Sauce', 'city_code' => '07'],
            ['state_id' => 14, 'name' => 'Intipuca', 'city_code' => '08'],
            ['state_id' => 14, 'name' => 'Lislique', 'city_code' => '09'],
            ['state_id' => 14, 'name' => 'Meanguera del Golfo', 'city_code' => '10'],
            ['state_id' => 14, 'name' => 'Nueva Esparta', 'city_code' => '11'],
            ['state_id' => 14, 'name' => 'Pasaquina', 'city_code' => '12'],
            ['state_id' => 14, 'name' => 'Poloros', 'city_code' => '13'],
            ['state_id' => 14, 'name' => 'San Alejo', 'city_code' => '14'],
            ['state_id' => 14, 'name' => 'San Jose', 'city_code' => '15'],
            ['state_id' => 14, 'name' => 'Santa Rosa de Lima', 'city_code' => '16'],
            ['state_id' => 14, 'name' => 'Yayantique', 'city_code' => '17'],
            ['state_id' => 14, 'name' => 'Yucuaiquin', 'city_code' => '18']
          ];
    
          if (Municipio::all()->count() < 1){
            foreach ($cities as $city) {
              Municipio::create([
                'nombre' => $city['name'],
                'codigo' => $city['city_code'],
                'departamento_id' => $city['state_id']
              ]);
            }
          }
    
    }
}
